#!/usr/bin/env bash
#
# fix-ocaml-protoc-pin.sh -- correct upstream vyconf's stale, self-contradictory
# `ocaml-protoc` version pin so the mirror actually builds.
#
# WHY: upstream vyos/vyconf's `rolling` HEAD ships this in vyconf.opam:
#
#   # The committed src/*_pbt.ml were generated by ocaml-protoc 2.x. Version 3.0
#   # emits private record types with presence tracking, which the hand-written
#   # call sites cannot construct. Pin to 2.x until the generated code + call
#   # sites are migrated to the 3.x API.
#   "ocaml-protoc" {build & < "3.0"}
#
# That comment + pin are STALE. At this snapshot the committed generated code
# was ALREADY migrated to the 3.x pbrt API but the pin/comment were left behind:
#   - src/vyconf_pbt.ml calls `Pbrt.Pp.pp_record_field ~first:true ...` -- the
#     `~first` labelled arg only exists in pbrt >= 3.0.
#   - src/dune's regeneration rule runs `ocaml-protoc --ml_out ...` -- the
#     double-dash `--ml_out` CLI is 3.x; ocaml-protoc 2.x uses `-ml_out`.
# So the `< 3.0` pin forces opam to install ocaml-protoc/pbrt 2.1, whose pbrt
# lacks `~first`, and `dune build -p vyconf` dies with
#   "This function ... is applied to too many arguments; maybe you forgot a `;'."
# at src/vyconf_pbt.ml (observed in the dozenos-1x package-build job: dozenos-1x
# opam-pins vyconf and this compile failure aborts libdozenosconfig).
#
# The build only succeeds against pbrt >= 3.0. Flip the pin to `>= "3.0"` so it
# matches the actually-committed 3.x generated code. Validated end-to-end in the
# build container: with `>= "3.0"`, opam installs ocaml-protoc/pbrt 4.1 and
# `dune build -p vyconf` compiles the full package (generated code AND the
# hand-written call sites the stale comment feared) cleanly.
#
# Idempotent + self-limiting. Only flips when BOTH conditions hold:
#   (a) vyconf.opam still carries a `< 3.0` ocaml-protoc pin, AND
#   (b) the committed src/vyconf_pbt.ml actually uses the 3.x `~first` API.
# If upstream later genuinely reverts the generated code to 2.x (no `~first`),
# condition (b) fails and the 2.x pin is left intact -- we do not fight a real
# upstream 2.x state. If the pin is already `>= 3.0` / unconstrained, no-op.
#
# Usage:
#   fix-ocaml-protoc-pin.sh <target-tree>
#
# LOCAL ONLY -- no network, no git.
set -euo pipefail

die() { printf 'fix-ocaml-protoc-pin: %s\n' "$*" >&2; exit 2; }

TARGET="${1:-}"
[ -n "$TARGET" ] || { echo "Usage: $0 <target-tree>" >&2; exit 2; }
[ -d "$TARGET" ] || die "not a directory: $TARGET"

OPAM="$TARGET/vyconf.opam"
PBT="$TARGET/src/vyconf_pbt.ml"

# This overlay is vyconf-specific; a tree with no vyconf.opam is a misuse.
[ -f "$OPAM" ] || die "no vyconf.opam in $TARGET -- is this the vyconf mirror?"

# Already fixed / not low-pinned -> nothing to do.
if ! grep -qE '"ocaml-protoc"[[:space:]]*\{[^}]*<[[:space:]]*"3\.0"' "$OPAM"; then
  echo "fix-ocaml-protoc-pin: no '< 3.0' ocaml-protoc pin in vyconf.opam -- nothing to do (skip)"
  exit 0
fi

# The `< 3.0` pin is present. Only overrule it if the committed generated code
# actually needs 3.x (uses the `~first` pbrt API). Otherwise upstream really is
# on 2.x and the pin is correct -- leave it be.
if [ -f "$PBT" ] && grep -qE 'pp_record_field[[:space:]]+~first' "$PBT"; then
  sed -i -E 's/("ocaml-protoc"[[:space:]]*\{[^}]*)<([[:space:]]*"3\.0")/\1>=\2/' "$OPAM"
  grep -qE '"ocaml-protoc"[[:space:]]*\{[^}]*>=[[:space:]]*"3\.0"' "$OPAM" \
    || die "flip did not take effect -- re-review vyconf.opam by hand"
  echo "fix-ocaml-protoc-pin: flipped ocaml-protoc pin '< 3.0' -> '>= 3.0' (committed src/vyconf_pbt.ml uses the 3.x '~first' API)"
else
  echo "fix-ocaml-protoc-pin: '< 3.0' pin present but src/vyconf_pbt.ml does NOT use the 3.x '~first' API -- upstream appears genuinely on 2.x; leaving the pin unchanged"
fi
